//
// Created by Besnik Nuro on 08/08/25.
//

#ifndef KERNEL_IMAGE_PROCESSING_NETPBMIMAGEFACTORY_H
#define KERNEL_IMAGE_PROCESSING_NETPBMIMAGEFACTORY_H


class NetpbmImageFactory {

};


#endif //KERNEL_IMAGE_PROCESSING_NETPBMIMAGEFACTORY_H
